### PR TITLE
Fix @scss unassigned variable error on grunt serve

### PR DESCRIPTION
**Pull request by dgca**
Change @if @else scss statement to assign default value and reassign if condition met. It was causing grunt to error out on `grunt serve` with an error of...
```
>> Undefined variable: "$base02".
>>   Line 38  Column 1  app/styles/themes/bold.scss
```
...with the error occurring on multiple files.

### CODE REVIEW

**Comment by wesbos** [comment]
I get this too and can confirm this PR fixes it

**Comment by micjamking** [comment]
Sorry guys, didn't mean to sleep on this one! Looks 👍

**Comment by wesbos** [comment]
Thanks friend!

**Comment by dgca** [comment]
Ah, nice! Thanks :-)

**Pull request merged**
