### PR TITLE
Updating The One theme with more precise rules.

### PR DESCRIPTION
**Pull request by benniemosher**
I created Issue #109 to get help trying to specify more finite rules.

### CODE REVIEW

**Comment by micjamking** [comment]
@benniemosher if you make the changes I recommended in #109, then your styles should come through as expected. I'll merge this in once you confirm your changes are in and ready to be released.

**Comment by benniemosher** [comment]
@micjamking This should be ready to be merged. It is as close as I can get it I think.

**Comment by micjamking** [comment]
@benniemosher looks good sir :+1:

**Comment by micjamking** [comment]
This is available in release [v0.5.12](https://github.com/micjamking/devtools-author/releases/tag/v0.5.12)

screen shot 2016-02-06 at 2 14 13 am

Thanks again for your contribution!

**Pull request merged**
